name: Build with Clang (Windows)

on:
  push:
    branches:
      - main  # Passe dies an deinen Branch an
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Läuft auf Windows
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      - name: Verify Clang Installation
        run: clang --version

      - name: Compile with Clang
        run: |
          mkdir build
          clang -Wall -Wextra -std=c17 -o build/program.exe src/*.c  # Falls du C nutzt
          # clang++ -Wall -Wextra -std=c++20 -o build/program.exe src/*.cpp  # Falls du C++ nutzt

      - name: Run Program (Optional)
        run: build\program.exe
