name: Build with Clang (Windows)

on:
  push:
    branches:
      - main  # Passe dies an deinen Branch an
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Aktualisierte Version

      - name: Install Vulkan SDK
        run: |
          choco install vulkan-sdk
          echo "VULKAN_SDK=$Env:VULKAN_SDK" >> $GITHUB_ENV
          echo "$Env:VULKAN_SDK\Bin" >> $Env:Path

      - name: Install SDL3
        run: choco install sdl3 --pre

      - name: Install GLM
        run: choco install glm

      - name: Download stb_image.h
        run: |
          mkdir include
          curl -o include/stb_image.h https://raw.githubusercontent.com/nothings/stb/master/stb_image.h

      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      - name: Verify Clang Installation
        run: clang --version

      - name: Verify Vulkan Installation
        run: vulkaninfo || echo "Vulkan SDK nicht gefunden!"

      - name: Compile with Clang
        run: |
          mkdir build
          clang++ -Wall -Wextra -std=c++20 -Iinclude -o build/program.exe src/*.cpp -lSDL3 -lvulkan

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: compiled-program
          path: build/program.exe
