name: Build with Clang (Windows)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Ermöglicht manuellen Start

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Vulkan Headers & Loader
        run: |
          mkdir Vulkan
          Invoke-WebRequest -Uri "https://github.com/KhronosGroup/Vulkan-Headers/archive/refs/heads/main.zip" -OutFile "Vulkan/vulkan-headers.zip"
          Invoke-WebRequest -Uri "https://github.com/KhronosGroup/Vulkan-Loader/archive/refs/heads/main.zip" -OutFile "Vulkan/vulkan-loader.zip"
          Expand-Archive -Path "Vulkan/vulkan-headers.zip" -DestinationPath "Vulkan/"
          Expand-Archive -Path "Vulkan/vulkan-loader.zip" -DestinationPath "Vulkan/"
        shell: pwsh

      - name: Install SDL3
        run: choco install sdl3 --pre -y

      - name: Install GLM
        run: choco install glm -y

      - name: Download stb_image.h
        run: |
          mkdir include
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/nothings/stb/master/stb_image.h" -OutFile "include/stb_image.h"
          if (!(Test-Path "include/stb_image.h")) { 
            Write-Host "Download fehlgeschlagen!" 
            exit 1 
          }
        shell: pwsh

      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      - name: Verify Clang Installation
        run: clang --version

      - name: Compile with Clang
        run: |
          mkdir build
          clang++ -Wall -Wextra -std=c++20 -Iinclude -IVulkan/Vulkan-Headers-main/include -o build/program.exe src/*.cpp -lSDL3main -lSDL3 -lvulkan-1
        shell: bash

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: compiled-program
          path: build/program.exe
