name: Build with Clang (Windows)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Ermöglicht manuellen Start

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Vulkan Runtime (Loader + Headers)
        run: |
          choco install vulkan-runtime -y
          echo "VULKAN_SDK=C:\VulkanSDK" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "C:\VulkanSDK\Bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: pwsh

      - name: Install SDL3
        run: choco install sdl3 --pre -y

      - name: Install GLM
        run: choco install glm -y

      - name: Download stb_image.h
        run: |
          mkdir include
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/nothings/stb/master/stb_image.h" -OutFile "include/stb_image.h"
          if (!(Test-Path "include/stb_image.h")) { 
            Write-Host "Download fehlgeschlagen!" 
            exit 1 
          }
        shell: pwsh

      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      - name: Verify Clang Installation
        run: clang --version

      - name: Verify Vulkan Installation
        run: |
          if (!(Get-Command vulkaninfo -ErrorAction SilentlyContinue)) { 
            Write-Host "Vulkan Runtime nicht gefunden!" 
            exit 1 
          }
          vulkaninfo
        shell: pwsh

      - name: Compile with Clang
        run: |
          mkdir build
          clang++ -Wall -Wextra -std=c++20 -Iinclude -o build/program.exe src/*.cpp -I"C:\VulkanSDK\Include" -L"C:\VulkanSDK\Lib" -lSDL3main -lSDL3 -lvulkan
        shell: bash

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: compiled-program
          path: build/program.exe
