name: Build with Clang (Windows)

on:
  push:
    branches:
      - main  # Passe dies an deinen Branch an
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Aktualisierte Version

      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      - name: Verify Clang Installation
        run: clang --version

      - name: Compile with Clang
        run: |
          mkdir build
          clang++ -Wall -Wextra -std=c++20 -o build/program.exe src/*.cpp

      - name: Upload Executable
        uses: actions/upload-artifact@v4  # Aktualisierte Version
        with:
          name: compiled-program
          path: build/program.exe
